//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_10.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noop
        ///noop
        ///addx 5
        ///addx 1
        ///addx 10
        ///addx -4
        ///noop
        ///addx -1
        ///noop
        ///addx 5
        ///addx -5
        ///addx 9
        ///addx 2
        ///addx -15
        ///addx 18
        ///addx 8
        ///addx -2
        ///noop
        ///addx -18
        ///addx 21
        ///addx 1
        ///addx -37
        ///addx 27
        ///addx -24
        ///addx 2
        ///addx 5
        ///addx -7
        ///addx 26
        ///addx -16
        ///addx 2
        ///addx 5
        ///addx -15
        ///noop
        ///addx 20
        ///addx 2
        ///addx 4
        ///addx -3
        ///addx 2
        ///noop
        ///addx 3
        ///addx 2
        ///addx 5
        ///addx -40
        ///addx 2
        ///addx 33
        ///addx -30
        ///addx 5
        ///addx 5
        ///addx 17
        ///addx -19
        ///addx 2
        ///addx 5
        ///addx 20
        ///addx -16
        ///addx 3
        ///addx -2
        ///addx 7
        ///noop
        ///addx -2
        ///addx 5
        ///addx 2
        ///add [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string puzzle_input {
            get {
                return ResourceManager.GetString("puzzle_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addx 15
        ///addx -11
        ///addx 6
        ///addx -3
        ///addx 5
        ///addx -1
        ///addx -8
        ///addx 13
        ///addx 4
        ///noop
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx 5
        ///addx -1
        ///addx -35
        ///addx 1
        ///addx 24
        ///addx -19
        ///addx 1
        ///addx 16
        ///addx -11
        ///noop
        ///noop
        ///addx 21
        ///addx -15
        ///noop
        ///noop
        ///addx -3
        ///addx 9
        ///addx 1
        ///addx -3
        ///addx 8
        ///addx 1
        ///addx 5
        ///noop
        ///noop
        ///noop
        ///noop
        ///noop
        ///addx -36
        ///noop
        ///addx 1
        ///addx 7
        ///noop
        ///noop
        ///noop
        ///addx 2
        ///addx 6
        ///noop
        ///noop
        ///noop
        ///noop
        ///noop
        ///addx 1
        ///noop
        ///noop
        ///addx 7
        ///addx 1
        ///noop
        ///addx -13
        ///addx 13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_input {
            get {
                return ResourceManager.GetString("test_input", resourceCulture);
            }
        }
    }
}
